/*
 * ISA project 2020
 * Author: Mirka Kolarikova (xkolar76)
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <time.h>
#include "isa_project_module.h"

//static variables for MIB objects
static char loginString[] = "xkolar76";
static int readwriteInt = 666;
static int readwriteInt_reserve;
#if _WIN32
	static char os[] = "Windows";
#elif __linux__
	static char os[] = "Linux";
#elif __APPLE__
        static char os[] = "Apple";
#elif BSD
	static char os[] = "BSD";
#else
	static char os[] = "other";
#endif

/** Initializes the isa_project_module module */
void
init_isa_project_module(void)
{
    const oid loginString_oid[] = { 1,3,6,1,3,22,1 };
    const oid timeString_oid[] = { 1,3,6,1,3,22,2 };
    const oid readwriteInt_oid[] = { 1,3,6,1,3,22,3 };
    const oid operatingSystem_oid[] = { 1,3,6,1,3,22,4 };

  DEBUGMSGTL(("isa_project_module", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("loginString", handle_loginString,
                               loginString_oid, OID_LENGTH(loginString_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("timeString", handle_timeString,
                               timeString_oid, OID_LENGTH(timeString_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("readwriteInt", handle_readwriteInt,
                               readwriteInt_oid, OID_LENGTH(readwriteInt_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("operatingSystem", handle_operatingSystem,
                               operatingSystem_oid, OID_LENGTH(operatingSystem_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_loginString(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     &loginString,
                                     sizeof(loginString)-1);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_loginString\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_timeString(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
time_t current_time = time(&current_time);
struct tm *ptm = gmtime(&current_time); //UTC time
char buffer[21];
strftime(buffer,21,"%FT%TZ", ptm);
    
    switch(reqinfo->mode) {

        case MODE_GET:

            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     &buffer,
                                     sizeof(buffer)-1);
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_timeString\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_readwriteInt(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                      &readwriteInt,
                                     sizeof(readwriteInt));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
	    readwriteInt_reserve = readwriteInt;

            break;

        case MODE_SET_FREE:
            break;

        case MODE_SET_ACTION:
	    readwriteInt = *(requests->requestvb->val.integer);

            break;

        case MODE_SET_COMMIT:

            break;

        case MODE_SET_UNDO:
	    readwriteInt = readwriteInt_reserve;
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_readwriteInt\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_operatingSystem(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                    &os,
                                     sizeof(os)-1);
		
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_operatingSystem\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
