/*
 * ISA project 2020
 * Author: Mirka Kolarikova (xkolar76)
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef ISA_PROJECT_MODULE_H
#define ISA_PROJECT_MODULE_H

/* function declarations */
void init_isa_project_module(void);
Netsnmp_Node_Handler handle_loginString;
Netsnmp_Node_Handler handle_timeString;
Netsnmp_Node_Handler handle_readwriteInt;
Netsnmp_Node_Handler handle_operatingSystem;

#endif /* ISA_PROJECT_MODULE_H */
